### ISSUE TITLE
Docs out-of-sync to CHANGELOG

### ISSUE THREAD

**Issue by randyzwitch** [jpjones76/SeisIO.jl#17]
In the changelog, you mention deprecating all the individual `read*` methods, but the docs still show them:

https://seisio.readthedocs.io/en/latest/src/Formats/fileformats.html#file-i-o-functions

Noticed this for the `readsegy` method, don't know how many others need to be removed

**Comment by jpjones76** [comment]
Argh, thank you. I'll fix that tonight. They definitely shouldn't be in the docs anymore.

**Comment by jpjones76** [comment]
Wow. The HTML files are _months_ behind current. Thank you for spotting this. I'm looking into what broke in the build process at the moment.

**Comment by jpjones76** [comment]
Hi, I updated the docs tonight and triggered a manual rebuild on ReadTheDocs. If you clear your cache and reload, are the HTML docs now current?

**Comment by randyzwitch** [comment]
Yup, looks like a whole new set of docs now, thanks!
