### ISSUE TITLE
integrity check failed?

### ISSUE THREAD

**Issue by mazhitu** [jpjones76/SeisIO.jl#20]
Hi jpjones76,

I am trying to download some TA stations but run into a warning saying integrity check failed.

For example, if I do
S1=get_data("FDSN","TA.061Z..LHZ",s="2012-08-20T10:50:00", t=4200, v=0, src="IRIS")
This is okay.

But if I do (change the starting time by 1 hour)
S2=get_data("FDSN","TA.061Z..LHZ",s="2012-08-20T11:50:00", t=4200, v=0, src="IRIS")
Then it says "RDMSEED: data integrity -- Steim-2 sequence #000015M  integrity check failed, last_data=4.2158346e8, should be xn=-1.2375288e9" and the waveform doesn't look right.

Would you please help me sort it out?

Thanks a lot,
Zhitu Ma

**Comment by jpjones76** [comment]
Well, one easy way to test whether it's an issue with SeisIO would be to write the request directly to disk with w=true and see if anything else reads it...

I have a few questions...
- How many stations produce this error? Are they all in the TA network?
- When did you first encounter this error? 
- Were you able to download data from the same stations with no issues before?
- Is this error confined to a specific time range? For example, suppose you download data a month before or a month after your example date. Do you still encounter this problem?

**Comment by jpjones76** [comment]
This should now be fixed on branch "master". Please let me know if you encounter this problem again.
