### ISSUE TITLE
Add SeisData into ASDF

### ISSUE THREAD

**Issue by kura-okubo** [jpjones76/SeisIO.jl#25]
Hello Josh,

Thank you for implementing `write_hdf5()` for output in ASDF format. I wonder if we could have an option to add SeisData into an existing ASDF file, like using `fid = h5open(filename, "cw")`. 

Cheers,
Kurama

**Comment by jpjones76** [comment]
Your timing is perfect. I am actually working on coding this in another window. :)

**Comment by jpjones76** [comment]
I'm testing my changes now. Here's what I'm adding:
* write_asdf with no special keywords will write to existing files by creating new traces in Waveforms/net.sta
* write_asdf with keyword ovr=true will overwrite (parts of) existing traces within Waveforms/net.sta, 
* write_asdf with keyword add=true will add new traces as needed to Waveforms/net.sta. 
  - I'm adding another keyword to let users control the size of each new trace, which is going to work with DateTime types, so if you want to initialize blank one month traces and then overwrite part of them with your trace data, you'll use something like `trace_len=Month(1)`. 

These changes will go live either tonight or tomorrow. 

I'd like to Skype with your group to explain these changes more and cover your use cases. If this isn't what your group needs, we can iterate on the write behavior until it matches what you intend to do. (The way that you're using ASDF seems very archetypal for working with large files, so I want to ensure that your work flow is intuitive and practical)

**Comment by kura-okubo** [comment]
Hi Josh, 

I think the update above is more than enough for my use, and general use as well.
I will use that function for not only download data but also intermediate files during post processing.

Cheers,
Kurama

**Comment by tclements** [comment]
Nice work on the ASDF read/write, Josh! I'm trying to read an ASDF file written with SeisIO with pyasdf
```julia 
S = get_data("FDSN", "TA.M22K..BHZ",s="2019-01-01",t=1)
SeisData with 1 channels (1 shown)
    ID: TA.M22K..BHZ                       
  NAME: Willow, AK, USA                    
   LOC: 61.7531 N, -150.12 E, 57.0 m       
    FS: 40.0                               
  GAIN: 5.03883e8                          
  RESP: a0 8.32666e17, f0 0.2, 6z, 11p     
 UNITS: m/s                                
   SRC: http://service.iris.edu/fdsnws/da… 
  MISC: 4 entries                          
 NOTES: 0 entries                          
     T: 2019-01-01T00:00:00.000 (0 gaps)   
     X: +8.540e+02                         
        +6.230e+02                         
            ...                            
        +5.330e+02                         
        (nx = 41)                          
     C: 0 open, 0 total
out = "seisiotest.h5"
write_hdf5(out,S)
```
Here is how I would go about creating the same file in python
```python
import obspy
import pyasdf
from obspy.clients.fdsn import Client
client = Client("IRIS")
st = client.get_waveforms("TA","M22K","","BHZ",obspy.UTCDateTime(2019,1,1),obspy.UTCDateTime(2019,1,1,0,0,1))
ds = pyasdf.ASDFDataSet("pyasdftest.h5", compression=None)
ds.add_waveforms(st,tag=st[0].stats.channel.lower())
ds.waveforms.TA_M22K.bhz                                               
1 Trace(s) in Stream:
TA.M22K..BHZ | 2019-01-01T00:00:00.000000Z - 2019-01-01T00:00:01.000000Z | 40.0 Hz, 41 samples
del ds
```

When reading the file made with SeisIO in python, there is a trailing underscore on the channel name
```python 
import pyasdf
ds = pyasdf.ASDFDataSet("seisiotest.h5")
ds.waveforms.TA_M22K
Contents of the data set for station TA.M22K:
    - Has a StationXML file
    - 1 Waveform Tag(s):
        bhz_
ds.waveforms.TA_M22K.bhz_
1 Trace(s) in Stream:
TA.M22K..BHZ | 2019-01-01T00:00:00.000000Z - 2019-01-01T00:00:01.000000Z | 40.0 Hz, 41 samples
```
Is the trailing underscore necessary for reading/writing? Removing/remembering the underscore forces some extra bookkeeping on the user

**Comment by jpjones76** [comment]
Oh! No, it's not necessary at all. I defined the channel name strings to follow @mdenolle's naming syntax in your group's test files. I'll drop the underscore from the tag.

I think I'll take that one step further and add a "tag=" KW; the tag is a freeform string in the file specification (e.g. Lion Krischer uses the tag "raw", rather than the three-letter component name, in the test volume that he sent me). 

I can patch this in tonight but it will be a couple of hours before I can start.

**Comment by tclements** [comment]
Awesome, no worries on the timing - this isn't urgent. I like the idea of a tag KW. I'm writing a write_hdf5 for CorrData based on your routine for SeisData

**Comment by jpjones76** [comment]
The tag change should now be live, along with removal of the trailing underscore.
