### ISSUE TITLE
S.loc = [-90.0, 0.0, 9300.0, 0.0, 0.0] got error

### ISSUE THREAD

**Issue by ihuangz** [jpjones76/SeisIO.jl#39]
Hi Joshua,
Thanks for sharing the package. It is convenient. 

But I got the following error following the tutorial: 
MethodError: Cannot `convert` an object of type Array{Float64,1} to an object of type InstrumentPosition

Is there something missing.

I am using SeisIO 1.0 in Mac.

Regards,

Zhouchuan

**Comment by jpjones76** [comment]
I'm very sorry that I let that slip through. That was a very old tutorial version, about a year outdated. I've rebuilt the documentation on readthedocs to use the correct page, but I don't understand why the documentation wasn't updating automatically. I've been doing manual rebuilds about once a week.

The tutorial on readthedocs should be current now, but the page location has changed slightly from last year. https://seisio.readthedocs.io/en/latest/src/Help/tutorial.html is the direct link.

If you get "page not found" errors, go to the documentation homepage at https://seisio.readthedocs.io/en/latest/ , and force your browser to reload (e.g. Shift + F5 in Chromium).

Please reply to this thread if you find any more documentation mistakes. I'm going to leave this issue open until we're certain this is resolved.

**Comment by jpjones76** [comment]
Did you encounter any other documentation issues, or is it OK to close this?
