### ISSUE TITLE
error in "mSEED.jl":428

### ISSUE THREAD

**Issue by ramindokht** [jpjones76/SeisIO.jl#4]
The command "search" is no longer supported, and it returns error calling the function: 
"mSEED.jl" at line 428.

This line has to be replaced with the following line:
(findfirst(isequal(read(fid, Char)), "DRMQ") > 0) || error("Scan failed due to invalid file type")

**Comment by jpjones76** [comment]
Thanks again for catching this bug. I'm closing this issue now because it appears that reading mSEED files again works correctly.
