### ISSUE TITLE
Bump HDF5.jl to 0.13+

### ISSUE THREAD

**Issue by shipengcheng1230** [jpjones76/SeisIO.jl#49]
Just out of curiosity, should we update the Compat for HDF5 using a higher version? For what I have known, there is one change since 0.13.0 that when indexing `HDF5Dataset`, the singleton dimension is automatically dropped, i.e `d[:,:,1] where d <: HDF5Dataset`, whereas previously not. Thanks for such great package!

**Comment by jpjones76** [comment]
I'd prefer to keep the current HDF5 Compat entry because of https://github.com/JuliaIO/HDF5.jl/issues/609; but I can update that if you start seeing unsatisfiable requirements errors.

**Comment by jpjones76** [comment]
https://github.com/JuliaIO/HDF5.jl/issues/609 has been fixed as of HDF5 0.13.5. I'll be updating SeisIO accordingly.
