### ISSUE TITLE
Bump compat for Blosc for "0.5.1, 0.6, 0.7"

### ISSUE THREAD

**Issue by tclements** [jpjones76/SeisIO.jl#58]
This is related to #49 -  can we bump compatibility for Blosc.jl to "0.5.1, 0.6, 0.7"? I'm having trouble bundling SeisIO with the new AWS.jl in a package due to SeisIO fixed on Blosc v0.5.1

**Comment by jpjones76** [comment]
Yep. Merged your PR into dev; will update master once the usual tests run. I did update HDF5 compatibility on master a couple of weeks ago (the HDF5.jl maintainers fixed the read slowdown issue)... but, weirdly, I didn't update dev. Very sorry!

**Comment by tclements** [comment]
Any chance you could merge the Blosc PR into master? Thanks!

**Comment by jpjones76** [comment]
This...wasn't merged? 

Holy sh--

**Comment by jpjones76** [comment]
It's done. Sorry...I really thought I'd merged it to master after your PR finished tests on dev.

**Comment by tclements** [comment]
Do you mind tagging a new release that includes these newer blosc versions? I'd like to incorporate these changes into another package that require blosc v0.6+. Thanks!

**Comment by jpjones76** [comment]
I'm working on final tests for the next release. Should be ready Friday (01-29), if the documentation for SAC v102.0 is correct. (I can't really check in SAC itself. In the past, IRIS wouldn't let me download it without a .gov or .edu email address, which was pretty hilarious as a postdoc at ualberta.ca...)

**Comment by tclements** [comment]
Awesome, thanks!
