### ISSUE TITLE
Expand NodalLoc to have x, y, & z positions  

### ISSUE THREAD

**Issue by tclements** [jpjones76/SeisIO.jl#63]
As of now, the `NodalLoc` has only an `x` position. For 2D and 3D nodal and DAS (horizontal + vertical) arrays, it would be helpful to have `x`, `y`, and `z` positions for 2D and 3D distance calculations. For instance, here is the geometry for the Brady Hot Springs geothermal DAS array: 

![image](https://user-images.githubusercontent.com/20441948/96610181-5775da80-12c9-11eb-8cee-e39d3564e950.png)

 Adding `y` and `z` to `NodalLoc` may add some overlap between `NodalLoc` and `UTMLoc`/`XYLoc` but `NodalData` already has fields for `ox`, `oy` and `oz`. 

I can submit a very simple PR with tests on this.

**Comment by jpjones76** [comment]
PR merged successfully into master. Going to close this. Thanks!
