### ISSUE TITLE
Error during data testing-Utils/test_units

### ISSUE THREAD

**Issue by shizhx3** [jpjones76/SeisIO.jl#97]
Some thing wrong when I run the SeisIO test packages. Help!!!

==================== Utils =====================
                         Utils/test_chanutils.jl
channel_match
cmatch_p!
                            Utils/test_findid.jl
  findid
                 Utils/test_get_seis_channels.jl
  get_seis_channels
                             Utils/test_guess.jl
  guess
    ability to determine file types unambiguously
    known file formats
    read_data with guess()
                            Utils/test_nx_max.jl
                    Utils/test_string_parsing.jl
  parsing
    how bad float strings parse:
      49.9.81 => 49.81
      .9f => 0.9
      .9fff183948913749817 => Inf
      +-+-+-1232.0 => -1232.0
      12a32.34a => 12.0
      threeve => 0.0
      Texa$ => 0.0
      13.13.13. => 13.0
      -.123efe => -0.123
    buf_to_double
                             Utils/test_units.jl
  units
    check that RandSeis uses valid UCUM units
WARNING: both IOExtras and Base export "closewrite"; uses of it in module StreamRequest must be qualified
WARNING: both IOExtras and Base export "closewrite"; uses of it in module ConnectionPool must be qualified
ERROR: LoadError: There was an error during testing
in expression starting at /home/zx/.julia/packages/SeisIO/9Jobh/test/Utils/test_units.jl:5
in expression starting at /home/zx/.julia/packages/SeisIO/9Jobh/test/runtests.jl:27
ERROR: Package SeisIO errored during testing

####################################
julia> versioninfo()
Julia Version 1.9.3
Commit bed2cd540a1 (2023-08-24 14:43 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 12 × Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-14.0.6 (ORCJIT, skylake)
  Threads: 1 on 12 virtual cores
Environment:
  LD_LIBRARY_PATH = :/home/zx/software/GMT-6.1.1/lib64
  JULIA_PKG_SERVER = https://mirrors.tuna.tsinghua.edu.cn/julia

**Comment by haakon-e** [comment]
@shizhx3 SeisIO is not really maintained anymore. There's an attempt to continue development on a fork, now called [SeisBase.jl](https://github.com/JuliaSeismo/SeisBase.jl)

**Comment by shizhx3** [comment]
OK, Thanks for giving me this information.
